name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create processed script
        run: |
          sed "s|'\${{ secrets.GOOGLE_APPS_SCRIPT_URL }}'|'${{ secrets.GOOGLE_APPS_SCRIPT_URL }}'|g" script.js > processed-script.js
          mv processed-script.js script.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
