name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Process Form Submission
        env:
          SCRIPT_URL: ${{ secrets.GOOGLE_APPS_SCRIPT_URL }}
        run: |
          # Just verify the secret is available
          if [ -n "$SCRIPT_URL" ]; then
            echo "Secret URL is available for form processing"
          fi
